version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"

    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"

    ports:
      - "15672:15672"
      - "5672:5672"

  microservice-a:
    image: "artcurty/microservice-a:latest"
    ports:
      - "9090:9090"

  microservice-c:
    image: "artcurty/microservice-c:latest"
    ports:
      - "9092:9092"

  microservice-d:
    image: "artcurty/microservice-d:latest"
    ports:
      - "9093:9093"

  microservice-b:
    image: "artcurty/microservice-b:latest"
    ports:
      - "9091:9091"
